### ISSUE TITLE
Custom connection port?

### ISSUE THREAD

**Issue by stereokai** [LeanKit-Labs/seriate#24]
How to specify a custom port?

Adding a `port` key to the `connectionConfig` does not work. It gets passed to `mssql.js` as `"server:port"` instead of `{ server: '...', port: 1234 }

Thanks.

**Comment by stereokai** [comment]
@ifandelse @rniemeyer Bump

**Comment by rniemeyer** [comment]
@stereokai - The config is passed directly on to `mssql` without manipulating the server/port properties. Would be happy to try to help you out. Do you have any additional information/errors?

**Comment by stereokai** [comment]
I don't know what was the problem, yesterday I deleted my node_modules directory and ran `npm install` again and it worked. I don't have an explanation.

Thank you anyway!
