### ISSUE TITLE
SqlContext Error: "pool is draining and cannot accept work"

### ISSUE THREAD

**Issue by Shockolate** [LeanKit-Labs/seriate#60]
Hello,
I am running into this error and I cannot seem to find an answer anywhere else on the internet.
I'm trying to perform several SQL commands when this occurs (i.e. several INSERTs and UPDATEs).
Other code has never run into this issue before when performing several INSERTS at once.

SqlContext Error. Failed on step \"StepIdHere\" with: \"pool is draining and cannot accept work\"

I would greatly appreciate any help.

**Comment by joshbang** [comment]
@Shockolate Did you ever figure out the problem? It just happened to me.

**Comment by Shockolate** [comment]
@joshbang I believe I switched libraries haha... node-mssql I think?
